server:
  port: 8789

spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8788

eureka:
  client:
    serviceUrl:
       # 向每个注册中心注册
      defaultZone: http://peer1:8761/eureka/,http://peer2:8769/eureka/
      #defaultZone: http://192.168.126.128:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点
  endpoint:
    health:
      show-details: ALWAYS #health endpoint是否必须显示全部细节。默认情况下, /actuator/health 是公开的，并且不显示细节。