eureka:
  client:
    serviceUrl:
      #defaultZone: http://peer1:8761/eureka/,http://peer2:8769/eureka/
      defaultZone: http://192.168.126.128:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-hi